# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.5.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # extra configuration settings
  chef_settings = {

      # our elasticsearch settings for Vagrant so it will use the private ip
      :elasticsearch => {
          :network => {
              :host => "_eth1:ipv4_"
          },
          :schedulerplugin => {
              :rpm => {
                  :version => "1.1.0-SNAPSHOT"
              }
          }
      }
  }

  config.omnibus.chef_version = :latest
  #config.berkshelf.enabled = true

  #ES Node 1
  config.vm.define "realsearch-es-node-1" do |es_config|
    es_config.vm.box = "chef/centos-6.5"
    es_config.vm.network "private_network", ip:"192.168.60.103"
    es_config.vm.hostname = "realsearch-es-node-1"
    es_config.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '512']
    end

    # Chef configurations
    es_config.vm.provision "chef_client" do |chef|
      chef.chef_server_url = "https://inf-chef2.altidev.net"
      chef.validation_key_path = "./../.chef/chef-validator.pem"

      # Add an environment
      chef.environment = "REALSearchTest"
      # Add a recipe
      chef.add_recipe "rf-elasticsearch"

      #Attributes
      chef.json.merge!(chef_settings)

      # Cleanup
      chef.delete_node = true
      chef.delete_client = true
    end
  end

  #ES Node 2
  config.vm.define "realsearch-es-node-2" do |es_config|
    es_config.vm.box = "chef/centos-6.5"
    es_config.vm.network "private_network", ip:"192.168.60.104"
    es_config.vm.hostname = "realsearch-es-node-2"
    es_config.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '512']
    end

    # Chef configurations
    es_config.vm.provision "chef_client" do |chef|
      chef.chef_server_url = "https://inf-chef2.altidev.net"
      chef.validation_key_path = "./../.chef/chef-validator.pem"

      # Add an environment
      chef.environment = "REALSearchTest"
      # Add a recipe
      chef.add_recipe "rf-elasticsearch"

      #Attributes
      chef.json.merge!(chef_settings)
      
      # Cleanup
      chef.delete_node = true
      chef.delete_client = true
    end
  end
end
