//  to run: sudo $MONGO_HOME/bin/mongo localhost:27017/realdoc --quiet seedData.js

//category
db.real_menu_parent.insert({"code":"Loan", "fieldName":"parent"})

db.real_menu_node.insert({"code":"Correspondence","types":["Borrower","Collections","Escrow","Miscellaneous","Notices","REALDoc Letters","Third Parties","Lender Correspondence"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Bankruptcy","types":["Claim/Case Info","Miscellaneous","Motions","Notices","Objections","Orders","Plans","Motion for Relief","Plan","Proof of Claim","Relief Order","Stipulation/Adequate Protection Order","Notice of Commencement"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Loss Mitigation Documents from Sparta","types":["No Title"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Real Estate Due Diligence","types":["Deed"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Collection and Delinquency","types":["Financial Income/Expense Statement"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Collateral","types":["Addenda","Affidavits","Agreements","Assignments","Deeds","Miscellaneous","Modifications","Note","Riders","Unrecorded Assignment","Attached Loan Mortgage","Mortgage","Short Sale","Special Short Sale","REO Deeds","HMP Modification","Assignment of Rents","Loan Agreement","Security Agreement","Rejected Loan Modification"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Settlement","types":["Closing Docs","Short Sale Closing Docs"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Origination","types":["Affidavits","Certs","Miscellaneous","Underwriting","Closing Documents","Preliminary Title Commitment","Underwriting Documents","Closing Disclosure Documents","Tax ID Verification","Asmnt of Rents/Misc. Financing","Commitment Letter","Construction Guaranty","Construction Loan Agreement","Current Statement","Environmental Indemnity","Financing Opinion","Above Documents for 1nd/3rd Mtg","Assignment of Rents, ect","Bond Closing Documents","Correspondence","Perm. Fin. Commitment Docs","Regulatory Agrmt. Mgt.","Security/Loan Agreement","Amortization Schedule","Borr. Auth. To Release Info","Fin. Request/Project Overview","Final Truth in Lending","Holdback Letter/Holdback Check","Lease Agreements","Loan Application","Sales Contract","Settlement Statement","Transmittal Summary","Bank/Investment Acc. Stmnts","CAIVRS Authorization Form","Credit Report","Income Documents for VA","Miscellaneous Verifications","Tax Returns","Title Searches","VA Form 26-6393, Loan Analysis","Verification of Deposits","Verification of Employment","Verification of Mortgage/Rent"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Property","types":["Agreements","Inspections","Miscellaneous","Property Management","Reports","Sale","Taxes","Trustee Sale","Valuation Report","Valuation Reports","Environmental Report","AVM","Property Report","SAM Appraisals","Developer Agreements","Leasing Guidelines","Maintenance Contracts","Management Agreements","Purchase/Payoff Offers","Renovation Plans/Budgets","Site Plans","Site Plan / Subdivision Plat","Survey/As Built","Zoning Info","Engineering Report"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Workout","types":["Financial","Closing Statement","Purchase/Payoff Offers","Workout Plans","Deficiency Judgement Execution","Loan Sale Negotiation","Management Approval","Miscellaneous","Payoff Letters/Estoppels","Prenegociation Agreements","Purchase Agreements","Recovery Arbitration","Recovery Litigation","Recovery Surety Bond Claim","Remic Issues","Valuation Updates"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Admin","types":["Invoices","Quality Assurance","Tax Credits"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Acquisition","types":["Complaint/Lis Pendens","Deed in Lieu","Miscellaneous","Motions","Notices","Orders","Trustee Sale"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"REO","types":["Agreements","Bids","Marketing","Settlements","Closing","Violations","Title","Contract","Miscellaneous","Title Policy and Sch","CFK","Pics","Finance","POA","Bills"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"HAFA","types":["Short Sale","Deed in Lieu"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Foreclosure","types":["Affidavits Review","Complaint/Lis Pendens"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"HAMP","types":["Others","Financial_Underwriting Documents","Rejected Loan Modification","Final Modification","Preliminary Modification"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Cr. Comm./Initial Deal Rev.","types":["Miscellaneous"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Comm. PROP. OPERATING BUDGETS","types":["2005.0","2006","2007","Commercial Prop. Operating Budgets 2000","Commercial Prop. Operating Budgets 2001","Commercial Prop. Operating Budgets 2002","Commercial Prop. Operating Budgets 2003","Commercial Prop. Operating Budgets 2004","Commercial Prop. Operating Budgets 2006","Commercial Prop. Operating Budgets 2007","Commercial Prop. Operating Budgets 2008","Commercial Prop. Operating Budgets 2009","Commercial Prop. Operating Budgets 2010"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Dev. and Const. Due Diligence","types":["Bkgd Invest. (Ctctr.,Arch.)","Miscellaneous"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Borrower","types":["Affidavits","Authorizations","Credit","Employment","Financials","Legal Docs","Miscellaneous Collections and Delinquency"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Origination and Closing","types":["Closing Documents","Miscellaneous","Underwriting Documents"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Sale","types":["Miscellaneous","Short Sale","Short Sale Closing Docs"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Miscellaneous","types":["Acknowledgements","Miscellaneous","Quality Assurance","UCC Statements"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Commercial","types":["Agreements","Approvals","Due Diligence","Financials","Legal Docs","Miscellaneous","Plans/Reports","REO","Sale Documents","Replacement Reserves"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Attached Loan","types":["Addenda","Affidavits","Note","Riders"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Collections","types":["Charge Off","Correspondence","Miscellaneous"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Servicing","types":["Miscellaneous","Adjustment Notices","Corporate Advances","Escrow Agent Agreement","Escrow Analysis","Loan Histories","Loan Servicing Invoice","Ocwen Loan Set-Up Sheets","Ocwen Year End Statements"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Insurance","types":["Binders","Cancellations","Certs","Claims","Correspondence","Invoices","Miscellaneous","Mortgage Insurance","Notices","Coml. Liability Ins.","Mortgage Insurance (VA, FHA, MI)","Miscellaneous Insurance"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Title","types":["Abstract","Affidavits","Miscellaneous","Reports","Searches","Title Policy/Trustee Sale/Abstract","Title Commitment","Title Work","Mechanics Lien"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Real Estate Taxes","types":["Preservation of Property Disbursement","Real Estate Taxes"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Comm. PROP. OP. STMNTS. 2007","types":["1st Quarter 2007","2nd Quarter 2007","4th Quarter 2007","Annual/Year End 2007","Comm. Prop. OP. Stmnts. April 2007","Comm. Prop. OP. Stmnts. August 2007","Comm. Prop. OP. Stmnts. December 2007","Comm. Prop. OP. Stmnts. February 2007","Comm. Prop. OP. Stmnts. January 2007","Comm. Prop. OP. Stmnts. July 2007","Comm. Prop. OP. Stmnts. June 2007","Comm. Prop. OP. Stmnts. March 2007","Comm. Prop. OP. Stmnts. May 2007","Comm. Prop. OP. Stmnts. November 2007","Comm. Prop. OP. Stmnts. October 2007","Comm. Prop. OP. Stmnts. September 2007","3rd Quarter 2007"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Comm. PROP. OP. STMNTS. 2005","types":["1st Quarter 2005","2nd Quarter 2005","3rd Quarter 2005","4th Quarter 2005","Annual/Year End 2005","Comm. Prop. OP. Stmnts. April 2005","Comm. Prop. OP. Stmnts. August  2005","Comm. Prop. OP. Stmnts. December 2005","Comm. Prop. OP. Stmnts. February 2005","Comm. Prop. OP. Stmnts. January 2005","Comm. Prop. OP. Stmnts. July 2005","Comm. Prop. OP. Stmnts. June 2005","Comm. Prop. OP. Stmnts. March 2005","Comm. Prop. OP. Stmnts. May 2005","Comm. Prop. OP. Stmnts. November 2005","Comm. Prop. OP. Stmnts. October 2005","Comm. Prop. OP. Stmnts. September 2005"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Comm. PROP. OP. STMNTS. 2006","types":["1st Quarter 2006","2nd Quarter 2006","3rd  Quarter 2006","4th Quarter 2006","Annual/Year End 2006","Comm. Prop. OP. Stmnts. April 2006","Comm. Prop. OP. Stmnts. August 2006","Comm. Prop. OP. Stmnts. December 2006","Comm. Prop. OP. Stmnts. February 2006","Comm. Prop. OP. Stmnts. January 2006","Comm. Prop. OP. Stmnts. July 2006","Comm. Prop. OP. Stmnts. June 2006","Comm. Prop. OP. Stmnts. March 2006","Comm. Prop. OP. Stmnts. May 2006","Comm. Prop. OP. Stmnts. November 2006","Comm. Prop. OP. Stmnts. October 2006","Comm. Prop. OP. Stmnts. September 2006"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Comm. PROP. OP. STMNTS. 2003","types":["1st Quarter 2003","2nd Quarter 2003","3rd Quarter 2003","4th Quarter 2003","Annual/Year End 2003","Comm. Prop. OP. Stmnts. April 2003","Comm. Prop. OP. Stmnts. August  2003","Comm. Prop. OP. Stmnts. December 2003","Comm. Prop. OP. Stmnts. February 2003","Comm. Prop. OP. Stmnts. January 2003","Comm. Prop. OP. Stmnts. July 2003","Comm. Prop. OP. Stmnts. June 2003","Comm. Prop. OP. Stmnts. March 2003","Comm. Prop. OP. Stmnts. May 2003","Comm. Prop. OP. Stmnts. November 2003","Comm. Prop. OP. Stmnts. October 2003","Comm. Prop. OP. Stmnts. September 2003"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Comm. PROP. OP. STMNTS. 2004","types":["1st Quarter 2004","2nd Quarter 2004","3rd Quarter 2004","4th Quarter 2004","Annual/Year End 2004","Comm. Prop. OP. Stmnts. April 2004","Comm. Prop. OP. Stmnts. August  2004","Comm. Prop. OP. Stmnts. December 2004","Comm. Prop. OP. Stmnts. February 2004","Comm. Prop. OP. Stmnts. January 2004","Comm. Prop. OP. Stmnts. July 2004","Comm. Prop. OP. Stmnts. June 2004","Comm. Prop. OP. Stmnts. March 2004","Comm. Prop. OP. Stmnts. May 2004","Comm. Prop. OP. Stmnts. November 2004","Comm. Prop. OP. Stmnts. October 2004","Comm. Prop. OP. Stmnts. September 2004"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Loss Mitigation Documents from TBW","types":["No Title"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Comm. PROP. OP. STMNTS. 2001","types":["1st Quarter 2001","2nd Quarter 2001","3rd Quarter 2001","4th Quarter 2001","Annual/Year End 2001","Comm. Prop. OP. Stmnts. April 2001","Comm. Prop. OP. Stmnts. August  2001","Comm. Prop. OP. Stmnts. December 2001","Comm. Prop. OP. Stmnts. February 2001","Comm. Prop. OP. Stmnts. January 2001","Comm. Prop. OP. Stmnts. July 2001","Comm. Prop. OP. Stmnts. June 2001","Comm. Prop. OP. Stmnts. March 2001","Comm. Prop. OP. Stmnts. May 2001","Comm. Prop. OP. Stmnts. November 2001","Comm. Prop. OP. Stmnts. October 2001","Comm. Prop. OP. Stmnts. September 2001"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Comm. PROP. OP. STMNTS. 2002","types":["1st Quarter 2002","2nd Quarter 2002","3rd Quarter 2002","4th Quarter 2002","Annual/Year End 2002","Comm. Prop. OP. Stmnts. April 2002","Comm. Prop. OP. Stmnts. August  2002","Comm. Prop. OP. Stmnts. December 2002","Comm. Prop. OP. Stmnts. February 2002","Comm. Prop. OP. Stmnts. January 2002","Comm. Prop. OP. Stmnts. July 2002","Comm. Prop. OP. Stmnts. June 2002","Comm. Prop. OP. Stmnts. March 2002","Comm. Prop. OP. Stmnts. May 2002","Comm. Prop. OP. Stmnts. November 2002","Comm. Prop. OP. Stmnts. October 2002","Comm. Prop. OP. Stmnts. September 2002"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"POA","types":["A - B","REO/Foreclosure Package (VA)","E - H","I - N","O - T","U - Z"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
db.real_menu_node.insert({"code":"Loan Servicing","types":["Miscellaneous"], "metadataFieldName":"metadata.category", "typeMetadataFieldName":"metadata.type", "parentCode":"Loan"});
