# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.5.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # extra configuration settings
  chef_settings = {


      :testing_setting => "1"
  }

  config.omnibus.chef_version = :latest
  #config.berkshelf.enabled = true

  #Rabbit Node 1
  config.vm.define "realsearch-searchservice-node-1" do |searchservice_config|
    searchservice_config.vm.box = "chef/centos-6.5"
    searchservice_config.vm.network "private_network", ip:"192.168.60.105"
    searchservice_config.vm.network "forwarded_port", guest:8080, host:8081
    searchservice_config.vm.hostname = "realsearch-searchservice-node-1"
    searchservice_config.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '512']
    end

    # Chef configurations
    searchservice_config.vm.provision "chef_client" do |chef|
      chef.chef_server_url = "https://inf-chef2.altidev.net"
      chef.validation_key_path = "./../.chef/chef-validator.pem"

      # Add an environment
      chef.environment = "REALSearchTest"
      # Add a recipe
      chef.add_recipe "rf-search-app::search-srv"

      # Cleanup
      chef.delete_node = true
      chef.delete_client = true

      #Attributes
      chef.json.merge!(chef_settings)
    end
  end
end
