# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.5.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.omnibus.chef_version = :latest
  config.berkshelf.enabled = true

  #ES Node 1
  config.vm.define "realsearch-haproxy" do |haproxy_config|
    haproxy_config.vm.box = "chef/centos-6.5"
    haproxy_config.vm.network "private_network", ip:"192.168.60.109"
    haproxy_config.vm.hostname = "realsearch-haproxy"
    haproxy_config.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '512']
    end

    # Chef configurations
    haproxy_config.vm.provision "chef_client" do |chef|
      chef.chef_server_url = "https://inf-chef2.altidev.net"
      chef.validation_key_path = "./../.chef/chef-validator.pem"

      # Add an environment
      chef.environment = "REALSearchTest"
      # Add a recipe
      chef.add_recipe "rf-haproxy"


      # Cleanup
      chef.delete_node = true
      chef.delete_client = true
    end
  end

end
